import { EventStatus } from '../../../shared/enums/event-status.enum';
import { EventType } from '../../../shared/enums/event-type.enum';

// Helper to create random date in the future
const randomFutureDate = (minDays: number, maxDays: number) => {
  const days = Math.floor(Math.random() * (maxDays - minDays + 1)) + minDays;
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString();
};

const randomCapacity = (min: number, max: number) => 
  Math.floor(Math.random() * (max - min + 1)) + min;

const randomBooked = (capacity: number) => 
  Math.floor(Math.random() * (capacity * 0.8));

// Moroccan cities
const cities = ['Casablanca', 'Marrakech', 'Rabat', 'Fes', 'Tangier', 'Agadir', 'Meknes', 'Oujda', 'Kenitra', 'Tetouan', 'Safi', 'Essaouira'];

export const fullEventsSeedData = [
  // MUSIC Category (5 events)
  {
    title: 'Gnawa World Music Festival',
    slug: 'gnawa-world-music-festival-2026',
    description: { text: 'Experience the mystical sounds of Gnawa music combined with jazz, rock, and blues.' },
    summary: 'Annual Gnawa music festival featuring international artists',
    category: 'Music',
    type: EventType.IN_PERSON,
    status: EventStatus.PUBLISHED,
    dateTime: { start: randomFutureDate(10, 40), end: null },
    location: { venue: 'Essaouira Medina', city: 'Essaouira', country: 'Morocco' },
    hero: { url: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&h=450&fit=crop', alt: 'Gnawa Festival' },
    capacity: randomCapacity(2000, 5000),
    bookedCount: 0,
  },
  {
    title: 'Jazz at the Kasbah',
    slug: 'jazz-kasbah-tangier-2026',
    description: { text: 'Intimate jazz performances in the historic Kasbah of Tangier.' },
    summary: 'Evening of smooth jazz in a stunning historic setting',
    category: 'Music',
    type: EventType.IN_PERSON,
    status: EventStatus.PUBLISHED,
    dateTime: { start: randomFutureDate(15, 60), end: null },
    location: { venue: 'Kasbah Museum', city: 'Tangier', country: 'Morocco' },
    hero: { url: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=800&h=450&fit=crop', alt: 'Jazz Concert' },
    capacity: randomCapacity(200, 500),
    bookedCount: 0,
  },
  {
    title: 'Rai Music Comeback Concert',
    slug: 'rai-music-concert-oujda',
    description: { text: 'Celebrating the golden era of Raï music with legendary performers.' },
    summary: 'Classic Raï music concert featuring iconic artists',
    category: 'Music',
    type: EventType.IN_PERSON,
    status: EventStatus.PUBLISHED,
    dateTime: { start: randomFutureDate(20, 70), end: null },
    location: { venue: 'Oujda Stadium', city: 'Oujda', country: 'Morocco' },
    hero: { url: 'https://images.unsplash.com/photo-1501612780327-45045538702b?w=800&h=450&fit=crop', alt: 'Rai Concert' },
    capacity: randomCapacity(3000, 8000),
    bookedCount: 0,
  },
  {
    title: 'Electronic Beats Marrakech',
    slug: 'electronic-beats-marrakech-2026',
    description: { text: 'International DJs bring electronic music to the Red City.' },
    summary: 'All-night electronic music festival',
    category: 'Music',
    type: EventType.IN_PERSON,
    status: EventStatus.PUBLISHED,
    dateTime: { start: randomFutureDate(25, 80), end: null },
    location: { venue: 'Palais Badi', city: 'Marrakech', country: 'Morocco' },
    hero: { url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&h=450&fit=crop', alt: 'Electronic Music' },
    capacity: randomCapacity(1500, 3000),
    bookedCount: 0,
  },
  {
    title: 'Andalusian Orchestra Performance',
    slug: 'andalusian-orchestra-fes',
    description: { text: 'Traditional Andalusian classical music performed by Fes orchestra.' },
    summary: 'Classical Andalusian music concert',
    category: 'Music',
    type: EventType.IN_PERSON,
    status: EventStatus.PUBLISHED,
    dateTime: { start: randomFutureDate(30, 90), end: null },
    location: { venue: 'Bab Makina', city: 'Fes', country: 'Morocco' },
    hero: { url: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=800&h=450&fit=crop', alt: 'Orchestra' },
    capacity: randomCapacity(500, 1000),
    bookedCount: 0,
  },

  // NIGHTLIFE Category (4 events)
  {
    title: 'Rooftop Sunset Party Casablanca',
    slug: 'rooftop-sunset-party-casa',
    description: { text: 'Dance the night away with ocean views and international DJs.' },
    summary: 'Premium rooftop party with stunning sunset views',
    category: 'Nightlife',
    type: EventType.IN_PERSON,
    status: EventStatus.PUBLISHED,
    dateTime: { start: randomFutureDate(5, 30), end: null },
    location: { venue: 'Sky 28 Lounge', city: 'Casablanca', country: 'Morocco' },
    hero: { url: 'https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=800&h=450&fit=crop', alt: 'Rooftop Party' },
    capacity: randomCapacity(200, 400),
    bookedCount: 0,
  },
  {
    title: 'Glow Party Rabat',
    slug: 'glow-party-rabat-2026',
    description: { text: 'Neon lights, UV paint, and electrifying music all night long.' },
    summary: 'Glow-in-the-dark themed dance party',
    category: 'Nightlife',
    type: EventType.IN_PERSON,
    status: EventStatus.PUBLISHED,
    dateTime: { start: randomFutureDate(12, 45), end: null },
    location: { venue: 'Club 7even', city: 'Rabat', country: 'Morocco' },
    hero: { url: 'https://images.unsplash.com/photo-1574391884720-bbc3740c59d1?w=800&h=450&fit=crop', alt: 'Glow Party' },
    capacity: randomCapacity(300, 600),
    bookedCount: 0,
  },
  {
    title: 'Latin Night at La Bodega',
    slug: 'latin-night-marrakech',
    description: { text: 'Salsa, bachata, and reggaeton all night with live band.' },
    summary: 'Latin music and dance party',
    category: 'Nightlife',
    type: EventType.IN_PERSON,
    status: EventStatus.PUBLISHED,
    dateTime: { start: randomFutureDate(18, 55), end: null },
    location: { venue: 'La Bodega', city: 'Marrakech', country: 'Morocco' },
    hero: { url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&h=450&fit=crop', alt: 'Latin Party' },
    capacity: randomCapacity(150, 300),
    bookedCount: 0,
  },
  {
    title: 'Beach Club Opening Night Agadir',
    slug: 'beach-club-opening-agadir',
    description: { text: 'Grand opening of the hottest beach club with international DJs.' },
    summary: 'Exclusive beach club opening party',
    category: 'Nightlife',
    type: EventType.IN_PERSON,
    status: EventStatus.PUBLISHED,
    dateTime: { start: randomFutureDate(22, 65), end: null },
    location: { venue: 'Agadir Beach Club', city: 'Agadir', country: 'Morocco' },
    hero: { url: 'https://images.unsplash.com/photo-1571266028243-d220c6c2e155?w=800&h=450&fit=crop', alt: 'Beach Club' },
    capacity: randomCapacity(400, 800),
    bookedCount: 0,
  },

  // ARTS Category (4 events)
  {
    title: 'Contemporary Moroccan Art Exhibition',
    slug: 'contemporary-art-exhibition-casablanca',
    description: { text: 'Showcasing the best of modern Moroccan artists.' },
    summary: 'Art exhibition featuring contemporary Moroccan artists',
    category: 'Arts',
    type: EventType.IN_PERSON,
    status: EventStatus.PUBLISHED,
    dateTime: { start: randomFutureDate(8, 35), end: null },
    location: { venue: 'Villa des Arts', city: 'Casablanca', country: 'Morocco' },
    hero: { url: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800&h=450&fit=crop', alt: 'Art Exhibition' },
    capacity: randomCapacity(100, 300),
    bookedCount: 0,
  },
  {
    title: 'Calligraphy Workshop with Master Artist',
    slug: 'calligraphy-workshop-fes',
    description: { text: 'Learn traditional Arabic calligraphy from a master.' },
    summary: 'Hands-on calligraphy workshop',
    category: 'Arts',
    type: EventType.IN_PERSON,
    status: EventStatus.PUBLISHED,
    dateTime: { start: randomFutureDate(14, 50), end: null },
    location: { venue: 'Fes Medina Arts Center', city: 'Fes', country: 'Morocco' },
    hero: { url: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&h=450&fit=crop', alt: 'Calligraphy' },
    capacity: randomCapacity(20, 50),
    bookedCount: 0,
  },
  {
    title: 'Street Art Walking Tour',
    slug: 'street-art-tour-rabat',
    description: { text: 'Explore Rabat\'s vibrant street art scene with local artists.' },
    summary: 'Guided tour of urban street art',
    category: 'Arts',
    type: EventType.IN_PERSON,
    status: EventStatus.PUBLISHED,
    dateTime: { start: randomFutureDate(19, 60), end: null },
    location: { venue: 'Rabat Medina', city: 'Rabat', country: 'Morocco' },
    hero: { url: 'https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=800&h=450&fit=crop', alt: 'Street Art' },
    capacity: randomCapacity(30, 60),
    bookedCount: 0,
  },
  {
    title: 'Pottery Making Masterclass',
    slug: 'pottery-masterclass-safi',
    description: { text: 'Create your own traditional Moroccan pottery pieces.' },
    summary: 'Traditional pottery workshop in the ceramics capital',
    category: 'Arts',
    type: EventType.IN_PERSON,
    status: EventStatus.PUBLISHED,
    dateTime: { start: randomFutureDate(24, 70), end: null },
    location: { venue: 'Safi Pottery School', city: 'Safi', country: 'Morocco' },
    hero: { url: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&h=450&fit=crop', alt: 'Pottery' },
    capacity: randomCapacity(15, 30),
    bookedCount: 0,
  },

  // SPORTS Category (3 events)
  {
    title: 'Desert Marathon Challenge',
    slug: 'desert-marathon-merzouga',
    description: { text: 'Ultimate endurance test across Sahara sand dunes.' },
    summary: '50km desert marathon race',
    category: 'Sports',
    type: EventType.IN_PERSON,
    status: EventStatus.PUBLISHED,
    dateTime: { start: randomFutureDate(35, 90), end: null },
    location: { venue: 'Merzouga Desert', city: 'Merzouga', country: 'Morocco' },
    hero: { url: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&h=450&fit=crop', alt: 'Desert Running' },
    capacity: randomCapacity(500, 1000),
    bookedCount: 0,
  },
  {
    title: 'Atlas Mountain Bike Race',
    slug: 'mountain-bike-race-atlas',
    description: { text: 'Challenging mountain bike competition through Atlas Mountains.' },
    summary: 'Extreme mountain biking event',
    category: 'Sports',
    type: EventType.IN_PERSON,
    status: EventStatus.PUBLISHED,
    dateTime: { start: randomFutureDate(40, 100), end: null },
    location: { venue: 'Imlil', city: 'Imlil', country: 'Morocco' },
    hero: { url: 'https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=800&h=450&fit=crop', alt: 'Mountain Biking' },
    capacity: randomCapacity(200, 400),
    bookedCount: 0,
  },
  {
    title: 'Beach Volleyball Tournament',
    slug: 'beach-volleyball-tournament-agadir',
    description: { text: 'Professional and amateur beach volleyball competition.' },
    summary: 'National beach volleyball championship',
    category: 'Sports',
    type: EventType.IN_PERSON,
    status: EventStatus.PUBLISHED,
    dateTime: { start: randomFutureDate(28, 75), end: null },
    location: { venue: 'Agadir Beach', city: 'Agadir', country: 'Morocco' },
    hero: { url: 'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=800&h=450&fit=crop', alt: 'Beach Volleyball' },
    capacity: randomCapacity(500, 1000),
    bookedCount: 0,
  },

  // FOOD & DRINK Category (3 events)
  {
    title: 'Tagine Cooking Class',
    slug: 'tagine-cooking-class-marrakech',
    description: { text: 'Learn to cook authentic Moroccan tagine from expert chefs.' },
    summary: 'Traditional Moroccan cooking workshop',
    category: 'Food & Drink',
    type: EventType.IN_PERSON,
    status: EventStatus.PUBLISHED,
    dateTime: { start: randomFutureDate(10, 40), end: null },
    location: { venue: 'Souk Cooking School', city: 'Marrakech', country: 'Morocco' },
    hero: { url: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&h=450&fit=crop', alt: 'Cooking Class' },
    capacity: randomCapacity(20, 40),
    bookedCount: 0,
  },
  {
    title: 'Moroccan Tea Ceremony & Pastries',
    slug: 'tea-ceremony-fes',
    description: { text: 'Experience the art of Moroccan tea preparation with traditional pastries.' },
    summary: 'Traditional tea ceremony workshop',
    category: 'Food & Drink',
    type: EventType.IN_PERSON,
    status: EventStatus.PUBLISHED,
    dateTime: { start: randomFutureDate(16, 50), end: null },
    location: { venue: 'Riad Fes', city: 'Fes', country: 'Morocco' },
    hero: { url: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=800&h=450&fit=crop', alt: 'Moroccan Tea' },
    capacity: randomCapacity(25, 50),
    bookedCount: 0,
  },
  {
    title: 'Seafood Festival by the Ocean',
    slug: 'seafood-festival-essaouira',
    description: { text: 'Fresh seafood prepared by top chefs in a beachside setting.' },
    summary: 'Ocean-to-table seafood festival',
    category: 'Food & Drink',
    type: EventType.IN_PERSON,
    status: EventStatus.PUBLISHED,
    dateTime: { start: randomFutureDate(21, 65), end: null },
    location: { venue: 'Essaouira Port', city: 'Essaouira', country: 'Morocco' },
    hero: { url: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&h=450&fit=crop', alt: 'Seafood' },
    capacity: randomCapacity(300, 600),
    bookedCount: 0,
  },

  // BUSINESS Category (3 events)
  {
    title: 'Fintech Summit Morocco',
    slug: 'fintech-summit-casablanca-2026',
    description: { text: 'Leading financial technology conference in North Africa.' },
    summary: 'International fintech conference and networking',
    category: 'Business',
    type: EventType.IN_PERSON,
    status: EventStatus.PUBLISHED,
    dateTime: { start: randomFutureDate(45, 100), end: null },
    location: { venue: 'Casablanca Finance City', city: 'Casablanca', country: 'Morocco' },
    hero: { url: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=450&fit=crop', alt: 'Business Conference' },
    capacity: randomCapacity(500, 1000),
    bookedCount: 0,
  },
  {
    title: 'Entrepreneurship Bootcamp',
    slug: 'entrepreneurship-bootcamp-rabat',
    description: { text: 'Intensive 3-day bootcamp for aspiring entrepreneurs.' },
    summary: 'Startup creation and business planning workshop',
    category: 'Business',
    type: EventType.IN_PERSON,
    status: EventStatus.PUBLISHED,
    dateTime: { start: randomFutureDate(32, 80), end: null },
    location: { venue: 'Rabat Technopolis', city: 'Rabat', country: 'Morocco' },
    hero: { url: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&h=450&fit=crop', alt: 'Entrepreneurship' },
    capacity: randomCapacity(100, 200),
    bookedCount: 0,
  },
  {
    title: 'Digital Marketing Conference',
    slug: 'digital-marketing-conference-tangier',
    description: { text: 'Latest trends in digital marketing and social media strategy.' },
    summary: 'Marketing professionals conference',
    category: 'Business',
    type: EventType.IN_PERSON,
    status: EventStatus.PUBLISHED,
    dateTime: { start: randomFutureDate(38, 90), end: null },
    location: { venue: 'Tangier Business Center', city: 'Tangier', country: 'Morocco' },
    hero: { url: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&h=450&fit=crop', alt: 'Marketing Conference' },
    capacity: randomCapacity(200, 400),
    bookedCount: 0,
  },

  // HOBBIES Category (3 events)
  {
    title: 'Chess Tournament Morocco Open',
    slug: 'chess-tournament-kenitra',
    description: { text: 'National chess championship for all skill levels.' },
    summary: 'Annual chess competition',
    category: 'Hobbies',
    type: EventType.IN_PERSON,
    status: EventStatus.PUBLISHED,
    dateTime: { start: randomFutureDate(26, 70), end: null },
    location: { venue: 'Kenitra Cultural Center', city: 'Kenitra', country: 'Morocco' },
    hero: { url: 'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=800&h=450&fit=crop', alt: 'Chess' },
    capacity: randomCapacity(100, 200),
    bookedCount: 0,
  },
  {
    title: 'Amateur Astronomy Night',
    slug: 'astronomy-night-merzouga',
    description: { text: 'Stargazing in the Sahara with telescopes and expert astronomers.' },
    summary: 'Desert stargazing experience',
    category: 'Hobbies',
    type: EventType.IN_PERSON,
    status: EventStatus.PUBLISHED,
    dateTime: { start: randomFutureDate(29, 75), end: null },
    location: { venue: 'Merzouga Desert Camp', city: 'Merzouga', country: 'Morocco' },
    hero: { url: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=800&h=450&fit=crop', alt: 'Stargazing' },
    capacity: randomCapacity(50, 100),
    bookedCount: 0,
  },
  {
    title: 'Vintage Car Show',
    slug: 'vintage-car-show-meknes',
    description: { text: 'Exhibition of classic and vintage automobiles.' },
    summary: 'Classic car exhibition and rally',
    category: 'Hobbies',
    type: EventType.IN_PERSON,
    status: EventStatus.PUBLISHED,
    dateTime: { start: randomFutureDate(33, 85), end: null },
    location: { venue: 'Place El Hedim', city: 'Meknes', country: 'Morocco' },
    hero: { url: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=450&fit=crop', alt: 'Vintage Cars' },
    capacity: randomCapacity(500, 1000),
    bookedCount: 0,
  },

  // HEALTH Category (2 events)
  {
    title: 'Yoga Retreat in the Atlas',
    slug: 'yoga-retreat-atlas-mountains',
    description: { text: 'Week-long yoga and meditation retreat in mountain sanctuary.' },
    summary: 'Wellness yoga retreat',
    category: 'Health',
    type: EventType.IN_PERSON,
    status: EventStatus.PUBLISHED,
    dateTime: { start: randomFutureDate(50, 110), end: null },
    location: { venue: 'Atlas Mountain Retreat', city: 'Imlil', country: 'Morocco' },
    hero: { url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=450&fit=crop', alt: 'Yoga Retreat' },
    capacity: randomCapacity(30, 60),
    bookedCount: 0,
  },
  {
    title: 'Wellness & Spa Day',
    slug: 'wellness-spa-day-marrakech',
    description: { text: 'Full day of hammam, massage, and relaxation treatments.' },
    summary: 'Traditional Moroccan spa experience',
    category: 'Health',
    type: EventType.IN_PERSON,
    status: EventStatus.PUBLISHED,
    dateTime: { start: randomFutureDate(15, 55), end: null },
    location: { venue: 'La Mamounia Spa', city: 'Marrakech', country: 'Morocco' },
    hero: { url: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&h=450&fit=crop', alt: 'Spa' },
    capacity: randomCapacity(40, 80),
    bookedCount: 0,
  },

  // HOLIDAY Category (2 events)
  {
    title: 'Ramadan Iftar Charity Dinner',
    slug: 'ramadan-iftar-charity-dinner-casa',
    description: { text: 'Community iftar dinner supporting local charities.' },
    summary: 'Charity iftar gathering',
    category: 'Holiday',
    type: EventType.IN_PERSON,
    status: EventStatus.PUBLISHED,
    dateTime: { start: randomFutureDate(60, 120), end: null },
    location: { venue: 'Hassan II Mosque Plaza', city: 'Casablanca', country: 'Morocco' },
    hero: { url: 'https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=800&h=450&fit=crop', alt: 'Iftar' },
    capacity: randomCapacity(1000, 3000),
    bookedCount: 0,
  },
  {
    title: 'Eid Al-Fitr Celebration',
    slug: 'eid-celebration-rabat-2026',
    description: { text: 'Community celebration with food, music, and entertainment.' },
    summary: 'Eid festivities and community gathering',
    category: 'Holiday',
    type: EventType.IN_PERSON,
    status: EventStatus.PUBLISHED,
    dateTime: { start: randomFutureDate(65, 125), end: null },
    location: { venue: 'Chellah Gardens', city: 'Rabat', country: 'Morocco' },
    hero: { url: 'https://images.unsplash.com/photo-1513407030348-c983a97b98d8?w=800&h=450&fit=crop', alt: 'Eid Celebration' },
    capacity: randomCapacity(2000, 5000),
    bookedCount: 0,
  },

  // SOCIAL Category (2 events)
  {
    title: 'Expats Networking Mixer Casablanca',
    slug: 'expats-networking-mixer-casa',
    description: { text: 'Monthly networking event for expats living in Morocco.' },
    summary: 'International community networking',
    category: 'Social',
    type: EventType.IN_PERSON,
    status: EventStatus.PUBLISHED,
    dateTime: { start: randomFutureDate(12, 45), end: null },
    location: { venue: 'Rick\'s Café', city: 'Casablanca', country: 'Morocco' },
    hero: { url: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?w=800&h=450&fit=crop', alt: 'Networking' },
    capacity: randomCapacity(80, 150),
    bookedCount: 0,
  },
  {
    title: 'Language Exchange Cafe',
    slug: 'language-exchange-cafe-tetouan',
    description: { text: 'Practice Arabic, French, English, and Spanish with locals and travelers.' },
    summary: 'Multilingual conversation meetup',
    category: 'Social',
    type: EventType.IN_PERSON,
    status: EventStatus.PUBLISHED,
    dateTime: { start: randomFutureDate(8, 35), end: null },
    location: { venue: 'Café Khalifa', city: 'Tetouan', country: 'Morocco' },
    hero: { url: 'https://images.unsplash.com/photo-1556761175-4b46a572b786?w=800&h=450&fit=crop', alt: 'Cafe Meetup' },
    capacity: randomCapacity(40, 80),
    bookedCount: 0,
  },
];
